auth.py
from flask import Blueprint, redirect, render_template, url_for, request, flash
from __init__ import db
from tables import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)

#Sets up login functionality
@auth.route("/login", methods = ['GET', 'POST'])
def login():
    #If the submit button is pressed
    if(request.method == 'POST'):
        #Retrieve values input in the email and password sections
        email = request.form.get("email")
        password = request.form.get("password")
        
        #Search for given email in database
        user = User.query.filter_by(email=email).first()
        #If the user exists, verify their password
        if(user):
            #If the given password when hashed is the same as the stored password, login
            if(check_password_hash(user.password, password)):
                flash('Successfully Logged In! Happy Posting!', category='success')
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            #If the hashed password is incorrect, return an error
            else:
                flash('Incorrect Passoword', category='error')
        #If the given email doesn't exist, return an error
        else:
            flash('Email given is not associated with an existing account', category='error')
    return render_template("login.html")

@auth.route("/sign-up", methods = ['GET', 'POST'])
def sign_up():
    #If the submit button is pressed
    if(request.method == 'POST'):
        #Retrieve all inputted values
        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        #Check if the given username or password already exist
        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        #Return an error if the given email exists
        if email_exists:
            flash('Email is already in use.', category='error')
        #Return an error if the given username exists
        elif username_exists:
            flash('Username is already in use.', category='error')
        #Return an error if the passwords don't match
        elif (password1 != password2):
            flash('Password don\'t match!', category='error')
        #Return an error if the given username is too short
        elif len(username) < 2:
            flash('Username is too short.', category='error')
        #Return an error if the given password is too short
        elif len(password1) < 6:
            flash('Password is too short.', category='error')
        #Return an error if the given email is too short
        elif len(email) < 4:
            flash("Email is invalid.", category='error')
        #Login if all tests are passed
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(
                password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('User created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("signup.html")

#Logout and redirect to home
@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, current_user
from tables import Comment, Post, User
from __init__ import db

views = Blueprint("views", __name__)

#Calls home html for home page
@views.route("/")
def home():
    return render_template("home.html")

#Calls archive html for archive page
@views.route("/archive")
#Forces user to login to view the page
@login_required
def archive():
    posts = Post.query.order_by(Post.date_created.desc()).all()
    return render_template("archive.html", user = current_user, posts = posts)

#Allows user to create a post
@views.route("/create-post", methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get('text')

        if not text:
            flash('Post is Empty', category='error')
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            return redirect(url_for('views.archive'))

    return render_template('create_post.html', user=current_user)

#Allows users to delete posts if they are the author
@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.author:
        flash('You do not have permission to delete this post.', category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted.', category='success')

    return redirect(url_for('views.archive'))


#Allows users to edit posts if they are the author
@views.route('/edit-post/<id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)

    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.author:
        flash('You do not have permission to edit this post.', category='error')

    if request.method == 'POST':
        post.text = request.form['text']
        db.session.commit()
        flash('Post has been edited!', category='success')
        return redirect(url_for('views.archive', id=post.id))

    return render_template('edit_post.html', post=post)


#Gets input from search bar and returns posts that fufill those qualifications
@views.route('/search')
def search():
    query = request.args.get('query')
    posts = Post.query.filter(Post.text.like(f'%{query}%')).all()

    return render_template('search.html', results=posts, query=query)

#Links to advanced search webpage
@views.route('/advanced-search')
def advanced_search():
    return render_template('advanced_search.html')

#Gets advanced search input and returns posts that fufill those qualifications
@views.route('/advanced-results')
def advanced_results():
    query = request.args.get('query')
    name = request.args.get('name')
    if query and not name:
        posts = Post.query.filter(Post.text.like(f'%{query}%')).all()
    if name and not query:
        posts = Post.query.filter(Post.author.like(f'%{name}%')).all()
    if query and name:
        posts = Post.query.filter(Post.text.like(f'%{query}%') & Post.author.like(f'%{name}%')).all()
    return render_template('advanced_results.html', results=posts)

#Displays user profile and all posts made by that user
@views.route("/user/<username>")
@login_required
def posts(username):
    user = User.query.filter_by(username = username).first()

    if not user:
        flash("No user with that username")
        return redirect(url_for("views.archive"))
    
    post = Post.query.filter_by(author=user.id).order_by(Post.date_created.desc()).all()
    return render_template("user_profile.html", user=current_user, posts=post, username = username)

#Displays specific post
@views.route("/post/<id>")
@login_required
def view_post(id):
    post = Post.query.get_or_404(id)

    if not post:
        flash("Post does not exist.", category='error')
    
    return render_template("post_view.html", post=post, user = current_user)


#Allows user to create and post comments
@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash("Comment cannot be empty!")
    else:
        post = Post.query.filter_by(id=post_id)
    if post:
        comment = Comment(text = text, author = current_user.id, post_id = post_id)
        db.session.add(comment)
        db.session.commit()
        flash("Successfully commented!", category="success")
    else:
        flash("The post you are attempting to comment on does not exist")
    return redirect(url_for("views.archive"))

#Allows user to delete comments if they are the post author or the comment author
@views.route("/delete-comment/<id>")
@login_required
def delete_comment(id):
    comment = Comment.query.filter_by(id=id).first()

    if not comment:
        flash("Comment does not exist.", category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()
        flash('Comment deleted.', category='success')

    return redirect(url_for('views.archive'))

#Allows users to edit comments if they are the comment author
@views.route('/edit-comment/<id>', methods=['GET', 'POST'])
@login_required
def edit_comment(id):
    comment = Comment.query.get_or_404(id)

    if not comment:
        flash("Comment does not exist.", category='error')
    elif current_user.id != comment.author:
        flash('You do not have permission to edit this comment.', category='error')

    if request.method == 'POST':
        comment.text = request.form['text']
        db.session.commit()
        flash('Comment has been edited!', category='success')
        return redirect(url_for('views.archive', id=comment.id))

    return render_template('edit_comment.html', comment=comment)

templates/advanced_search.html
{% extends "layout.html" %}
{% block title %}
Advanced Search
{% endblock %}
{% block content %}
<br>
<form method = "GET" action="{{ url_for('views.advanced_results') }}">
    <h3 align=" center">
        Advanced Search
    </h3>
    <div class = "form-group">
        <label for="name">Author Id</label>
        <input type="number" name="name" class="form-control" placeholder="Enter Author Id"/>
        <br>
        <label for="text">Post Content</label>
        <input type="text" name="query" class="form-control" placeholder="Enter Text"/>
        <br>
        <div align = "center">
        <button class = "btn btn-custom" type="Submit">
            Search
        </button>
        </div>
    </div>
    </form>
{% endblock %}

templates/archive.html
{% extends "posts_div.html" %}
{% block title %}
Archive
{% endblock %}
{% block header %}
<br>
Archived Posts
<form method="GET" action="{{ url_for('views.search') }}">
        <br>
        <input type="text" name="query" class="form-control" placeholder="Search...">
        <div align="center">
                <button class="btn btn-custom" type="submit">Search</button>
        </div>
</form>

<div align="right">
        <a href = "/create-post"><button type = "button" class="btn btn-custom btn-lg">Create a Post</button></a>
</div>
{% endblock %}

templates/create_post.html
{% extends "layout.html" %}
{% block title %}
Create A Post
{% endblock %}
{% block content %}
<br>
    <h1 align = "center"> Create A Post</h1>
    <form method="POST">
        <textarea name="text" id="text" class = "form-control"></textarea>
        <br>
        <div align = "center">
            <button type="submit" class = "btn btn-lg btn-custom">Post</button>
        </div>
    </form>
<br>
<div align="center">
    <a href = "/archive"><button type = "button" class="btn btn-secondary btn-lg">Back</button></a>
</div>
{% endblock %}

templates/edit_comment.html
{% extends "layout.html" %}
{% block title %}
Edit Post
{% endblock %}
{% block content %}
<br>
    <h1 align = "center"> Edit Comment</h1>
    <form method="POST">
        <textarea name="text" id="text" class = "form-control">{{comment['text'] }}</textarea>
        <br>
        <div align = "center">
            <button type="submit" class = "btn btn-lg btn-custom">Comment</button>
        </div>
    </form>
<br>
<div align="center">
    <a href = "/archive"><button type = "button" class="btn btn-secondary btn-lg">Back</button></a>
</div> 
{%endblock%}

templates/edit_post.html
{% extends "layout.html" %}
{% block title %}
Edit Post
{% endblock %}
{% block content %}
<br>
    <h1 align = "center"> Edit Post</h1>
    <form method="POST">
        <textarea name="text" id="text" class = "form-control">{{post['text'] }}</textarea>
        <br>
        <div align = "center">
            <button type="submit" class = "btn btn-lg btn-custom">Post</button>
        </div>
    </form>
<br>
<div align="center">
    <a href = "/archive"><button type = "button" class="btn btn-secondary btn-lg">Back</button></a>
</div> 
{%endblock%}

templates/home.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}
<br>
<div align = "center">
    <h2>Welcome to VoiceBox!</h2>
    {% if current_user.is_authenticated %}
        <p>Go to the Archives section to view posts made by our community!</p>
        <a href="{{ url_for('auth.logout') }}">
            <button class = "btn btn-custom" type="button">Log Out</button>
        </a>
    {% else %}
        <p>Make sure to sign in!</p>
        <a href="{{ url_for('auth.login') }}">
            <button class = "btn btn-custom" type="button">Log In</button>
        </a>
        <a href="{{ url_for('auth.sign_up') }}">
            <button class = "btn btn-custom" type="button">Sign Up</button>
        </a>
    {%endif%}
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.png')}}" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
          $('.alert').alert()
        })
      </script>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <img src="{{ url_for('static', filename='logo1.png')}}" alt="logo" id="homelogo">
    <nav class="navbar navbar-expand-lg navbar-custom">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav center">
            <a class="nav-item nav-link" href="{{ url_for('views.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('views.archive') }}">Archive</a>
        </a>
        </div>
        </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
        {% if category != "success" %}
        <div class="alert alert-danger alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-dismiss="alert"></button>
        </div>
          {% else %}
        <div class="alert alert-success alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-dismiss="alert"></button>
        </div>
        {% endif %}

        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <button type="button" name="dark_light" title="Toggle dark/light mode" id="theme-toggle">
        <img src="{{ url_for('static', filename='night.png')}}" width="50" height="50" id = "dark">
        <img src="{{ url_for('static', filename='day.png')}}" width="55" height="55" id="light">
    </button>
    <footer>
        <p>&copy; 2024 Elijah Simmonds</p>
    </footer>
</body>

</html>
<script>

$(document).ready(function() {
  //Creates a const to save the current theme
  const savedTheme = localStorage.getItem('theme');

  //Sets the site to dark or light mode depending on what's saved
  if (savedTheme) {
    $('body').addClass(savedTheme);
    $(".btn-custom").addClass(savedTheme);
  //If nothing is saved, default to light mode
  } else {
    $('body').addClass('light-mode'); 
    $(".btn-custom").addClass('light-mode');
  }

  //When the dark mode toggle button is clicked, toggle between light and dark mode
  $('#theme-toggle').click(function() {
    $('body').toggleClass('light-mode dark-mode');
    $('.btn-custom').toggleClass('light-mode dark-mode');
    //Switch the icons
    $("#dark").toggle();
    $("#light").toggle();

    //Save the theme as it's current mode
    const currentTheme = $('body').hasClass('dark-mode') ? 'dark-mode' : 'light-mode';
    localStorage.setItem('theme', currentTheme);
  });
});
</script>

<style>
  #homelogo {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 15%;
  }

  .navbar-custom {
    background-color: #27a9dc;
  }

  .custom-placeholder::placeholder {
    color: white;
  }

  .center {
    text-align: center;
  }

  .navbar-expand-lg {
    display: flex!important;
    justify-content: space-around;
    flex-basis: auto;
  }

  #theme-toggle{
    background: none;
    color: inherit;
    border: none;
    padding: 0;
    font: inherit;
    cursor: pointer;
    outline: inherit;
  }

  #dark {
    display: show;
    position: fixed;
    bottom: 60px;
    right: 8px;
  }

  #light {
    display: none;
    position: fixed;
    bottom: 60px;
    right: 8px;
  }

  footer {
    text-align: center;
    padding: 6px 0;
    background-color: #27a9dc;
    position: fixed;
    width: 100%;
    bottom: 0;
  }

  a:link {
    color: white;
    text-decoration: none;
    text-align: center;
  }

  a:visited {
    color: white;
    text-decoration: none;
    text-align: center;
  }

  a:hover {
    color: white;
    text-decoration: none;
    text-align: center;
  }

  a:active {
    color: white;
    text-decoration: none;
    text-align: center;
  }

  body {
    padding-bottom: 100px
  }

  body.dark-mode {
    background-color: #201c1c;
    color: white;
  }

  body.dark-mode a {
    color: white;
  }

  body.light-mode {
    background-color: white;
    color: black;
  }
  
  body.light-mode a {
    color: black;
  }

  footer.dark-mode {
    color: white;
  }
  footer.dark-mode p {
    color: #201c1c;
  }
  footer.light-mode {
    color: #111;
  }
  footer.light-mode p {
    color: white;
  }

  .btn-custom:hover{
    color: white;
    background-color: #27a9dc;
  }

  .btn-custom.light-mode{
    color: white;
    background-color: #27a9dc;
  }

  .btn-custom.dark-mode{
    color: black;
    background-color: #27a9dc;
  }
</style>

templates/login.html
{% extends "layout.html" %}
{% block title %}
Login
{% endblock %}
{% block content %}
<br>
<form method = "POST">
<h3 align=" center">
    Login
</h3>
<div class = "form-group">
    <label for="email">Email Address</label>
    <input type="text" name="email" id="email" class="form-control" placeholder="Enter Email"/>
    <br>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" class="form-control" placeholder="Enter Password"/>
    <br>
    <div align = "center">
    <button class = "btn btn-custom" type="Submit">
        Submit
    </button>
    </div>
</div>
</form>
<br>
<div align = "center">
    <p>Make sure to sign up if you haven't already.</p>
    <a href="{{ url_for('auth.sign_up') }}">
        <button class = "btn btn-custom" type="button">Sign Up</button>
    </a>
</div>
{% endblock %}

templates/post.html
{% extends "posts_div.html" %}
{% block title %}
{{username}}'s Posts
{% endblock %}
{% block header %}
<h1 align="center">{{username}}'s Posts</h1>
<h2 align="center">User ID: {{user.id}}</h2>
{% endblock %}
{% block footer %}
<div align="center">
    <a href = "/home"><button type = "button" class="btn btn-secondary btn-lg">Back</button></a>
</div>
{% endblock %}

templates/post_view.html
{% extends "layout.html" %}
{% block title %}
{{post.user.username}} - "{{post.text}}"
{% endblock %}
{% block content %}
<br>
<br>
</h1>
<div id="posts">
        <div class="card border-dark">
                <div class="card-header d-flex justify-content-between align-items-center btn-custom">
                        <a href="/user/{{post.user.username}}" class="text-dark">{{post.user.username}}</a>
                        {%if user.id == post.author%}
                        <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-light btn-outline-secondary dropdown-toggle"
                                        data-toggle="dropdown"></button>
                                <ul class="dropdown-menu">
                                        <li><a href="/delete-post/{{post.id}}"
                                                        class="dropdown-item text-dark">Delete</a></li>
                                        <li><a href="/edit-post/{{post.id}}" class="dropdown-item text-dark">Edit</a>
                                        </li>
                                </ul>
                        </div>
                        {%endif%}
                </div>
                <div class="card-body">
                        <div class="card-text">{{post.text}}</div>
                        <br>
                        <form class="input-group mb-3" method="POST" action="/create-comment/{{post.id}}">
                                <input type="text" name="text" id="text" class="form-control"
                                        placeholder="Got something to add?">
                                <button type="submit" class="btn btn-custom">Comment</button>
                        </form>
                        <div class="collapse" id="comments-{{post.id}}">
                                <div class="card">
                                        <div class="card-body" id="comments-expanded-{{post.id}}">
                                                {% for comment in post.comments%}
                                                <div class="d-flex justify-content-between align-items-center">
                                                        <div>
                                                                <a href="/user/{{comment.user.username}}"
                                                                        class="text-dark">{{comment.user.username}}</a>:
                                                                {{comment.text}}
                                                                <div>
                                                                        <small
                                                                                class="text-muted">{{comment.date_created}}</small>
                                                                        {%if user.id == post.author or user.id ==
                                                                        comment.author%}
                                                                        <div class="btn-group">
                                                                                <button type="button"
                                                                                        class="btn btn-sm btn-custom btn-outline-secondary dropdown-toggle"
                                                                                        data-toggle="dropdown"></button>
                                                                                <ul class="dropdown-menu">
                                                                                        <li><a href="/delete-comment/{{comment.id}}"
                                                                                                        class="dropdown-item text-dark">Delete</a>
                                                                                        </li>
                                                                                        {%if user.id == comment.author%}
                                                                                        <li><a href="/edit-comment/{{comment.id}}"
                                                                                                        class="dropdown-item text-dark">Edit</a>
                                                                                        </li>
                                                                                        {%endif%}
                                                                                </ul>
                                                                        </div>
                                                                        {%endif%}
                                                                </div>
                                                        </div>
                                                </div>
                                                {%endfor%}
                                        </div>
                                </div>
                        </div>
                        <p class="card-text">
                                {%if post.comments|length > 0%}
                                <a data-toggle="collapse" href="#comments-{{post.id}}" role="button">
                                        {% if post.comments|length == 1 %}
                                        <small class="text-dark">View {{post.comments|length}} Comment</small>
                                        {%else%}
                                        <small class="text-dark">View {{post.comments|length}} Comments</small>
                                        {%endif%}
                                </a>
                                {%else%}
                                <small class="text-muted">No Comments</small>
                                {%endif%}
                        </p>
                </div>
                <div class="card-footer btn-custom text-dark">
                        <a href="/post/{{post.id}}" class="text-dark">{{post.date_created}}</a>
                </div>
        </div>
        <br>
</div>
<br>
<div align="center">
        <a href="/archive"><button type="button" class="btn btn-secondary btn-lg">Back</button></a>
</div>
{% endblock %}

templates/search.html
{% extends "layout.html" %}
{% block title %}
Search Results
{% endblock %}
{% block content %}
<br>
<a class="nav-item nav-link" href="{{ url_for('views.advanced_search') }}">Advanced Search</a>
<br>
<h1>Search Results</h1>
<br>
{% for post in results %}
<div class="card border-dark">
    <div class="card-header d-flex justify-content-between align-items-center">
            <a href="/user/{{post.user.username}}">{{post.user.username}}</a>
            {%if current_user.id|string == post.author%}
            <div class = "btn-group">
                    <button type= "button" class = "btn btn-sm btn-custom dropdown-toggle" data-toggle="dropdown"></button>
                    <ul class="dropdown-menu">
                            <li><a href="/delete-post{{post.id}}" class = "dropdown-item">Delete</a></li>
                    </ul>
            </div>
            {%endif%}
    </div>
    <div class = "card-body">
            <div class = "card-text">{{post.text}}</div>
    </div>
    <div class = "card-footer text-muted">
            {{post.date_created}}
    </div>
</div>
<br>
{%endfor%}
{% endblock %}

templates/signup.html
{% extends "layout.html" %}
{% block title %}
Sign Up
{% endblock %}
{% block content %}
<br>
<form method = "POST">
<h3 align=" center">
    Sign Up
</h3>
<div class = "form-group">
    <label for="email">Email Address</label>
    <input type="text" name="email" id="email" class="form-control" placeholder="Enter Email"/>
    <br>
    <label for="username">Username</label>
    <input type="text" name="username" id="username" class="form-control" placeholder="Enter Username"/>
    <br>
    <label for="password1">Password</label>
    <input type="password" name="password1" id="password1" class="form-control" placeholder="Enter Password"/>
    <br>
    <label for="password2">Enter Password Again</label>
    <input type="password" name="password2" id="password2" class="form-control" placeholder="Enter Password Again"/>
    <br>
    <div align = "center">
    <button class = "btn btn-custom" type="Submit">
        Sign Up
    </button>
    </div>
</div>
</form>
<br>
<div align = "center">
    <p>If you already have an account, click here to log in.</p>
    <a href="{{ url_for('auth.login') }}">
        <button class = "btn btn-custom" type="button">Log In</button>
    </a>
</div>
{% endblock %}

templates/user_profile.html
{% extends "posts_div.html" %}
{% block title %}
{{username}}'s Posts
{% endblock %}
{% block header %}
<h1 align="center">{{username}}'s Posts</h1>
<h2 align="center">User ID: {{user.id}}</h2>
{% endblock %}
{% block footer %}
<div align="center">
    <a href = "/archive"><button type = "button" class="btn btn-secondary btn-lg">Back</button></a>
</div>
{% endblock %}